<a href="https://colab.research.google.com/github/anaismveras/coding-practice/blob/ai-learning-linkedin-learning/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Array creation and attributes

In [ ]:
import numpy as np
# turning a list into an array
nums = [1,2,3,4,5]

array1 = np.array(nums)

print(array1)

[1 2 3 4 5]


In [ ]:
zero_array = np.zeros(5)
# an array of 0s
print(zero_array)

[0. 0. 0. 0. 0.]


In [ ]:
one_array = np.ones(3)
# an array of ones
print(one_array)

[1. 1. 1.]


In [ ]:
range_array = np.arange(1,10,2)
# arange(starting_num, ending_num, jump by num(optional))
print(range_array)

range_array2 = np.arange(1,10)
# arange(starting num, ending num)
print(range_array2)

range_array3 = np.arange(10)
# arange(ending_num) - will start from 0
print(range_array3)

[1 3 5 7 9]
[1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
random_array = np.random.randint(1, 100, 5)
# randint(staring number, ending number, number of elements in the array)
print(random_array)

[55 49 54 43 70]


In [ ]:
random_matrix = np.random.rand(3, 8)
# random.rand(rows, columns)
print(random_matrix)

[[0.60186213 0.27828397 0.4026119  0.21002276 0.70764905 0.34850405
  0.18949743 0.79212835]
 [0.12152381 0.9168355  0.63541371 0.90881373 0.44016356 0.41248329
  0.05607408 0.54863345]
 [0.36182233 0.04251154 0.45583729 0.55694204 0.44320036 0.31453535
  0.33178815 0.16491156]]


In [ ]:
shape = range_array.shape
# Shape = the dimensions of the array, returns a tuple where each number
# indicates the size of the corresponding dimension
print(shape)

shape2 = random_matrix.shape
# because the array of the matrix has 3 arrays inside and 8 elements each
print(shape2)

# Purpose -
# Data Validation: Quickly check if data has the expected number of rows/columns.
# Debugging: Essential for fixing errors where operations expect specific data dimensions.
# Data Transformation: Crucial for reshaping data for analysis or model input.
# Memory Efficiency: Helps manage and optimize memory usage for large datasets.
# ML Integration: Required to prepare data in formats expected by machine learning frameworks.
# Performance: Aids in writing efficient code, especially with large NumPy arrays.

(5,)
(3, 8)


In [ ]:
size = random_array.size
print(size)

size2 = random_matrix.size
print(size2)
# size is the length of the array basically - total number of elements in the array

5
24


In [ ]:
dtype = range_array.dtype
# getting the datatype of an array - in this case integer
print(dtype)

int64


In [ ]:
print(range_array.ndim)
# dimension of an array

1


# Array Operations

In [ ]:
import numpy as np

array_one = np.array([1,2,3,4,5])
array_two = np.array([6,7,8,9,10])

sum = array_one + array_two
# adding the two arrays
print(sum)

subtraction = array_one - array_two
print(subtraction)

multiplication = array_one * array_two
print(multiplication)

division = array_one / array_two
print(division)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [ ]:
mean = np.mean(array_one)
# getting the mean of the array - mean is the average
print(mean)

median = np.median(array_one)
# getting the median of the array - the number in the middle of all numbers ordered smallest to large
print(median)

whole_sum = np.sum(array_one)
# getting the sum of the array - summing all the numbers together
print(whole_sum)

max = np.max(array_one)
# getting the max of the array - largest num in array
print(max)

min = np.min(array_one)
# getting the min of the array - smallest num in array
print(min)

3.0
3.0
15
5
1


In [ ]:
greater_than = array_one > 3
print(greater_than)

less_than = array_one < 3
print(less_than)

# returns a boolean array for each number in the arrays
# these are done element by element

[False False False  True  True]
[ True  True False False False]


In [ ]:
# Broadcasing

result = array_one + 5
# doing an math operation for each element
print(result)

[ 6  7  8  9 10]


# Indexing and Slicing

In [ ]:
import numpy as np

another_array_one = np.array([10, 20, 30, 40, 50])

secondelement = another_array_one[1]
# getting the second element of the array
print(secondelement)

20


In [ ]:
# if you dont know the count but you want the second last
print(another_array_one[-2])
# will index from the end

40


In [ ]:
# take a piece out of the whole chunk
sliced_array = another_array_one[1:4]
# [starting index of element : ending index of element(minus 1 to the element indicated)] - will get the element up to 3 index
print(sliced_array)

[20 30 40]


In [ ]:
step_array = another_array_one[::2]
# I need an entire array but only every second element, step by 2
print(step_array)

[10 30 50]


In [ ]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
# getting the second elelment of the second row
element = matrix[1,1]
print(element)

# getting the second row
second_row = matrix[1, :]
print(second_row)

second_column = matrix[:, 1]
print(second_column)

5
[4 5 6]
[2 5 8]


In [ ]:
# finding all the nulls in an array
data = np.array([1,2,3,np.nan,4,5])
missing = np.isnan(data)
# will return a boolean array for each element
print(missing)

[False False False  True False False]


In [ ]:
data_fill = np.nan_to_num(data, nan=100)
print(data_fill)

[  1.   2.   3. 100.   4.   5.]


# Linear Algebra and statistics

In [ ]:
import numpy as np

multidimensional_array1 = np.array([[1,2], [3,4]])
multidimensional_array2 = np.array([[5,6], [7,8]])

# getting the matrix multiplcation of each array per column
multiplcation = np.dot(multidimensional_array1, multidimensional_array2)
print(multiplcation)

# matrix multiplcation goes like:
# [[A,B], [C,D]]
# [[E,F], [G,H]]
# [[(A*E)+(B*G) (A*F)+(B*H)]
# [(C*E)+(D*G) (C*F)+(D*H)]]

[[19 22]
 [43 50]]


In [ ]:
inversion= np.linalg.inv(multidimensional_array1)
# getting the inversion of the matrix
print(inversion)

# Purpose -
# ML Model Understanding: Helps grasp the math behind many ML algorithms (e.g., linear regression, PCA).
# Data Transformation: Useful for complex feature engineering or reverting transformations in specific domains like signal processing.
# Equation Solving: Basis for solving systems of linear equations in optimization or resource allocation tasks.
# Error Correction/Calibration: Can be used to correct sensor data or calibrate systems.
# Advanced Analytics: Essential background for working with specialized analytical tools or custom libraries that rely on linear algebra.

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
eval, evect = np.linalg.eig(multidimensional_array1)
# getting the eigenvalues and eigenvectors of the matrix
print(eval)
print(evect)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
data1 = np.array([1,2,3,4,5])
mean = np.mean(data1)
# standard deviation - measure of how spread out the number are in a dataset
standard_deviation = np.std(data1)

print(mean)
print(std_dev)

3.0
1.4142135623730951


In [ ]:
data2 = np.array([11,12,13,14,15])
#  correlation coefficient - indicates the strength and direction of a linear
# relationship between two random variables
# only represented in +1, -1 or 0
# +1 - positive - one variable increase the other variables also tends to increase
# -1 - negative - one variable increase, the other variable tends to decrease
# 0 - a weak or no linear relationship between two variables
correlation = np.corrcoef(data1, data2)
print(correlation)

[[1. 1.]
 [1. 1.]]


# Write a NumPy array to a file

In [ ]:
np.savetxt('output-numpy.csv', multidimensional_array1, delimiter=',')
# save to a csv file

In [ ]:
np.save('output-npy.npy', multidimensional_array1)
# save to a npy file
new_matrix = np.load('output-npy.npy')

In [ ]:
import pandas as pd

df = pd.DataFrame(multidimensional_array1)
df.to_excel('output-pandas.xlsx')
# save to a excel file
# need to use pandas